### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pepijn98** [Pepijn98/Mashu#1]
## General
- [x] Change language to TypeScript
- [x] Update README, add a list of commands with detailed descriptions and example usage

## Commands
- [x] Update suggestion description
- [x] Add an example property
- [x] Add an subCommands property
~- [ ] Add a shortDescription property~

### Mute
- [x] Check db for expired mute times
- [x] Mute time
- [x] Persistent mute
~- [ ] Use mongodb's TTL property~

### Note
- [x] Add notes about users
- [x] Remove notes about users
- [x] Update notes about users
- [x] View notes from users

**Comment by Pepijn98** [comment]
Finished all the things :)
